from typing import Protocol, runtime_checkable


@runtime_checkable
class CapturePort(Protocol):
    """Port interface for a screen-capture backend (e.g. VidGear)."""

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def is_recording(self) -> bool: ...
    def start_recording(self) -> None: ...
    def stop_recording(self) -> str | None: ...
    def set_record_directory(self, directory: str) -> None: ...
