from typing import Protocol, runtime_checkable


@runtime_checkable
class CapturePort(Protocol):
    """Port interface for a video capture adapter (e.g. OBS WebSocket)."""

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def is_recording(self) -> bool: ...
    def start_recording(self) -> None: ...
    def stop_recording(self) -> str | None: ...
    def set_record_directory(self, directory: str) -> None: ...
    def set_scene(self, scene_name: str) -> None: ...
